image:
    - Visual Studio 2017
environment:
    PYTHON: "C:\\Python37-x64"
    PYTHON_VERSION: "3.7.x"
    PYTHON_ARCH: "64"
platform:
    - x64
configuration:
    - Debug
    - Release
clone_folder: c:\projects\clamp_cast
before_build:
    - cmd: cd c:\projects\clamp_cast & mkdir build & cd build & ..\conan.bat & cmake .. -A x64 -DBUILD_TESTING=On"
build:
    project: c:\projects\clamp_cast\build\clamp_cast.sln
    parallel: true
install:
    - set PATH=%PYTHON%;%PYTHON%/Scripts/;%PATH%
    - pip.exe install conan --upgrade
    - pip.exe install conan_package_tools
    - conan user
    - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan --force
test_script:
    - cmd: c:\projects\clamp_cast\build\bin\clamp_cast_tests.exe
