image:
  - Visual Studio 2017
platform:
  - x64
configuration:
  - Debug
  - Release
clone_folder: c:\projects\clamp_cast
before_build:
  - cmd: cd c:\projects\clamp_cast
  - cmd: mkdir build
  - cmd: cd build
  - cmd: ..\conan.bat
  - cmd: cmake .. -A x64 -DBUILD_TESTING=On
build:
  project: c:\projects\clamp_cast\build\clamp_cast.sln
  parallel: true
install:
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: where pip
  - cmd: pip.exe install conan
  - cmd: cd ..
  - cmd: where conan
  - cmd: conan user
  - cmd: conan --version
  - cmd: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - cmd: cd c:\projects\clamp_cast
test_script:
  - cmd: c:\projects\clamp_cast\build\bin\clamp_cast_tests.exe
